"""empty message

Revision ID: 0ae0f4fc309d
Revises: 0ba21dbda404
Create Date: 2022-05-27 21:44:27.202437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae0f4fc309d'
down_revision = '0ba21dbda404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE venue SET seeking_talent = False WHERE seeking_talent IS NULL')

    op.alter_column('venue', 'seeking_talent', nullable=False, default=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
