"""empty message

Revision ID: 2f610fda2102
Revises: e78568dca5c3
Create Date: 2022-05-29 22:37:09.916419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f610fda2102'
down_revision = 'e78568dca5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venues', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'seeking_venues')
    # ### end Alembic commands ###
