"""empty message

Revision ID: 5f4e42f2a67b
Revises: 2f610fda2102
Create Date: 2022-05-29 22:38:23.918059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4e42f2a67b'
down_revision = '2f610fda2102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'seeking_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
